/**
 * Transform Portal customer and lead data to SAP BusinessPartner format
 * This utility handles the mapping from Portal database format to SAP API format
 */

import { getEffectiveLeadName } from '../leads/getEffectiveLeadName';

/**
 * Split full name into first name and last name
 * @param {string} fullName - Full name string
 * @returns {Object} Object with firstName and lastName
 */
function splitFullName(fullName) {
  if (!fullName || typeof fullName !== 'string') {
    return { firstName: '', lastName: '' };
  }

  const nameParts = fullName.trim().split(/\s+/);
  
  if (nameParts.length === 1) {
    return { firstName: nameParts[0], lastName: '' };
  }
  
  // First part is first name, rest is last name
  const firstName = nameParts[0];
  const lastName = nameParts.slice(1).join(' ');
  
  return { firstName, lastName };
}

/**
 * Extract zip code from address string
 * @param {string} address - Full address string
 * @returns {string|null} Zip code if found, null otherwise
 */
function extractZipCode(address) {
  if (!address) return null;
  
  // Singapore zip codes are 6 digits
  const zipMatch = address.match(/\b\d{6}\b/);
  return zipMatch ? zipMatch[0] : null;
}

/**
 * Transform Portal customer and lead data to SAP BusinessPartner format
 * @param {Object} customer - Portal customer object
 * @param {Object} lead - Portal lead object (optional, for address/contact info)
 * @returns {Object} SAP BusinessPartner format data
 */
export function transformToSAPBusinessPartner(customer, lead = null) {
  // Base BusinessPartner data
  const businessPartner = {
    // CardCode will be auto-generated by SAP on creation.
    // We intentionally DO NOT send CardCode when creating from Portal,
    // so that SAP can manage CardCode generation.
    Series: 71, // 70 = Customer, 71 = Lead (default: 71)
    CardName: (lead ? getEffectiveLeadName(lead) : null) || customer.customer_name || '',
    CardType: 'cLid', // Lead type
    Valid: 'tYES',
  };

  // Add email if available
  if (customer.email) {
    businessPartner.EmailAddress = customer.email;
  }

  // Add phone if available
  if (customer.phone_number) {
    businessPartner.Phone1 = customer.phone_number;
  }

  // Add address information from lead if available
  if (lead) {
    const addresses = [];
    const addressData = {};

    // Build address from lead fields (using new detailed fields)
    if (lead.block || lead.unit || lead.address || lead.building || lead.street) {
      // Address Name: Use block-unit or building-street or address
      const addressName = lead.block && lead.unit 
        ? `#${lead.block}-${lead.unit}`
        : (lead.building && lead.street)
        ? `${lead.building}-${lead.street}`.substring(0, 50)
        : lead.address || lead.building || 'Main Address';

      addressData.AddressName = addressName.substring(0, 50); // SAP limit
      addressData.AddressType = 'bo_BillTo'; // Bill Address
      // Note: SAP doesn't accept 'Default' field in BPAddress

      // Street address (prefer street field, then address, combine with building if available)
      let streetValue = '';
      if (lead.street) {
        streetValue = lead.street;
      } else if (lead.address) {
        streetValue = lead.address;
      }
      
      // Combine building with street if building exists (SAP doesn't have separate Building field in BPAddress)
      if (lead.building && streetValue) {
        addressData.Street = `${lead.building}, ${streetValue}`.substring(0, 100);
      } else if (lead.building) {
        addressData.Street = lead.building.substring(0, 100);
      } else if (streetValue) {
        addressData.Street = streetValue.substring(0, 100);
      }

      // Block
      if (lead.block) {
        addressData.Block = lead.block.substring(0, 100);
      }

      // Building/Floor/Room (from unit, or building if no unit)
      if (lead.unit) {
        addressData.BuildingFloorRoom = lead.unit.substring(0, 100);
      } else if (lead.building && !streetValue) {
        // Use building in BuildingFloorRoom if no unit and no street
        addressData.BuildingFloorRoom = lead.building.substring(0, 100);
      }

      // Postcode (prefer postcode field, then extract from address)
      if (lead.postcode) {
        addressData.ZipCode = lead.postcode.substring(0, 20);
      } else {
        const zipCode = extractZipCode(lead.address);
        if (zipCode) {
          addressData.ZipCode = zipCode;
        }
      }

      // Country (prefer country field, default to Singapore)
      if (lead.country) {
        // Convert country name to code if needed
        const countryCode = lead.country.toLowerCase().includes('singapore') ? 'SG' : lead.country.substring(0, 2).toUpperCase();
        addressData.Country = countryCode;
      } else {
        addressData.Country = 'SG';
      }
      
      addressData.City = 'Singapore'; // Default, can be extracted from address if needed

      addresses.push(addressData);

      // Add bo_ShipTo address with same mapping (append "- 1" to AddressName)
      const shipToAddress = { ...addressData };
      shipToAddress.AddressType = 'bo_ShipTo'; // Shipping address
      shipToAddress.AddressName = `${addressData.AddressName} - 1`.substring(0, 50);
      addresses.push(shipToAddress);
    }

    // Add addresses if any
    if (addresses.length > 0) {
      businessPartner.BPAddresses = addresses;
    }

    // Add contact employee information
    const contactEmployees = [];
    const contactData = {};

    if (lead.full_name || customer.customer_name) {
      // Use first_name and last_name if available, otherwise split full_name
      let firstName, lastName;
      if (lead.first_name && lead.last_name) {
        firstName = lead.first_name;
        lastName = lead.last_name;
      } else {
        const fullName = lead.full_name || customer.customer_name;
        const split = splitFullName(fullName);
        firstName = split.firstName;
        lastName = split.lastName;
      }

      contactData.Name = `Contact1`;
      contactData.FirstName = firstName.substring(0, 100);
      contactData.LastName = lastName.substring(0, 100);

      // Add phone if available
      if (lead.handphone || customer.phone_number) {
        contactData.Phone1 = (lead.handphone || customer.phone_number).substring(0, 20);
      }

      // Add email if available
      if (lead.email || customer.email) {
        contactData.E_Mail = (lead.email || customer.email).substring(0, 100);
      }

      // Position is optional
      contactData.Position = null;

      contactEmployees.push(contactData);
    }

    // Add contact employees if any
    if (contactEmployees.length > 0) {
      businessPartner.ContactEmployees = contactEmployees;
    }
  } else {
    // If no lead, create minimal address from customer
    if (customer.customer_address) {
      const billToAddress = {
        AddressName: 'Main Address',
        AddressType: 'bo_BillTo',
        Street: customer.customer_address.substring(0, 100),
        Country: 'SG',
        City: 'Singapore'
        // Note: SAP doesn't accept 'Default' field in BPAddress
      };

      // Add bo_ShipTo address with same mapping (append "- 1" to AddressName)
      const shipToAddress = {
        AddressName: 'Main Address - 1',
        AddressType: 'bo_ShipTo',
        Street: customer.customer_address.substring(0, 100),
        Country: 'SG',
        City: 'Singapore'
      };

      businessPartner.BPAddresses = [billToAddress, shipToAddress];
    }
  }

  // Log the complete payload being sent to SAP for debugging
  console.log('📤 SAP BusinessPartner Payload:', JSON.stringify(businessPartner, null, 2));

  return businessPartner;
}

/**
 * Validate BusinessPartner data before sending to SAP
 * @param {Object} businessPartnerData - BusinessPartner data to validate
 * @returns {Object} Validation result with isValid and errors
 */
export function validateBusinessPartnerData(businessPartnerData) {
  const errors = [];

  // CardName is required
  if (!businessPartnerData.CardName || businessPartnerData.CardName.trim() === '') {
    errors.push('CardName is required');
  }

  // CardName max length is 100
  if (businessPartnerData.CardName && businessPartnerData.CardName.length > 100) {
    errors.push('CardName exceeds maximum length of 100 characters');
  }

  // CardCode validation if provided
  if (businessPartnerData.CardCode) {
    // CardCode max length is typically 15
    if (businessPartnerData.CardCode.length > 15) {
      errors.push('CardCode exceeds maximum length of 15 characters');
    }
    // CardCode should be alphanumeric
    if (!/^[a-zA-Z0-9]+$/.test(businessPartnerData.CardCode)) {
      errors.push('CardCode must be alphanumeric');
    }
  }

  // Validate email format if provided
  if (businessPartnerData.EmailAddress) {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(businessPartnerData.EmailAddress)) {
      errors.push('EmailAddress is not a valid email format');
    }
  }

  return {
    isValid: errors.length === 0,
    errors
  };
}

